package grisu.web;

import grisu.backend.model.job.JobStat;
import grisu.jcommons.constants.Constants;
import grisu.jcommons.utils.MemoryUtils;
import grisu.jcommons.utils.WalltimeUtils;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Panel;
import com.vaadin.ui.Table;
import com.vaadin.ui.VerticalLayout;

public class JobDetailsComponent extends CustomComponent{

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Panel jobDetPanel;
	@AutoGenerated
	private VerticalLayout jobDetLayout;
	@AutoGenerated
	private Table tblDets;
	@AutoGenerated
	private Table tblProps;

	private static Logger log = LoggerFactory.getLogger(Thread.currentThread().getClass());

	public JobDetailsComponent() {
		// TODO Auto-generated constructor stub
		
		log.debug("Inside constructor");
		
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		
		tblDets.addContainerProperty("property", String.class, null);
		tblDets.addContainerProperty("value", String.class, null);
		
		tblDets.setVisibleColumns(new String [] {"property", "value"});
		tblDets.setColumnHeaders(new String [] {"Property", "Value"});
		
		tblProps.addContainerProperty("property", String.class, null);
		tblProps.addContainerProperty("value", String.class, null);
		
		tblProps.setVisibleColumns(new String[] {"property", "value"});
		tblProps.setColumnHeaders(new String [] {"Property",  "value"});
				
		tblDets.setCaption("Additional job properties");
		tblProps.setCaption("Job Properties");
		tblDets.setPageLength(7);
		tblProps.setPageLength(9);
		
		log.debug("Exiting constructor");
	}

	public void populate(JobStat job) {
		// TODO Auto-generated method stub

		log.debug("Inside populate()");
		
		tblDets.removeAllItems();
		tblProps.removeAllItems();
		
		List<String> jobProperties = new ArrayList<String>();
		jobProperties.add(Constants.JOBNAME_KEY);
		jobProperties.add(Constants.COMMANDLINE_KEY);
		jobProperties.add(Constants.NO_CPUS_KEY);
		jobProperties.add(Constants.MEMORY_IN_B_KEY);
		jobProperties.add(Constants.WALLTIME_IN_MINUTES_KEY);
		jobProperties.add(Constants.SUBMISSIONLOCATION_KEY);
		jobProperties.add(Constants.SUBMISSION_TIME_KEY);
		jobProperties.add(Constants.APPLICATIONNAME_KEY);
		jobProperties.add(Constants.APPLICATIONVERSION_KEY);

		if(job!=null){
		
			Map<String, String> propertyMap = job.getProperties();
			
			String val=null;
			for(String prop:propertyMap.keySet()){
				val =  propertyMap.get(prop);
				if(jobProperties.contains(prop)){
					if(prop.equalsIgnoreCase(Constants.MEMORY_IN_B_KEY)){
						val=MemoryUtils.humanReadableByteCount(Long.parseLong(val), false);
					}
					if(prop.equalsIgnoreCase(Constants.WALLTIME_IN_MINUTES_KEY)){
						val=WalltimeUtils.convertSeconds(Integer.parseInt(val)*60);
					}
					if(prop.equalsIgnoreCase(Constants.SUBMISSION_TIME_KEY)){
						Date d = new Date(Long.parseLong(val));
						val=d.toString();
					}
					tblProps.addItem(new Object [] {prop, val},null);
				}
				else{
					tblDets.addItem(new Object [] {prop, val},null);
				}
			}
		}
		
		tblDets.setSortContainerPropertyId("property");
		tblDets.setSortAscending(true);
		tblDets.sort();
		
		log.debug("Exiting populate()");
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("-1px");
		
		// jobDetPanel
		jobDetPanel = buildJobDetPanel();
		mainLayout.addComponent(jobDetPanel);
		mainLayout.setExpandRatio(jobDetPanel, 1.0f);
		
		return mainLayout;
	}

	@AutoGenerated
	private Panel buildJobDetPanel() {
		// common part: create layout
		jobDetPanel = new Panel();
		jobDetPanel.setImmediate(false);
		jobDetPanel.setWidth("100.0%");
		jobDetPanel.setHeight("-1px");
		
		// jobDetLayout
		jobDetLayout = buildJobDetLayout();
		jobDetPanel.setContent(jobDetLayout);
		
		return jobDetPanel;
	}

	@AutoGenerated
	private VerticalLayout buildJobDetLayout() {
		// common part: create layout
		jobDetLayout = new VerticalLayout();
		jobDetLayout.setImmediate(false);
		jobDetLayout.setWidth("100.0%");
		jobDetLayout.setHeight("-1px");
		jobDetLayout.setMargin(false);
		jobDetLayout.setSpacing(true);
		
		// tblProps
		tblProps = new Table();
		tblProps.setImmediate(false);
		tblProps.setWidth("100.0%");
		tblProps.setHeight("-1px");
		jobDetLayout.addComponent(tblProps);
		
		// tblDets
		tblDets = new Table();
		tblDets.setImmediate(false);
		tblDets.setWidth("100.0%");
		tblDets.setHeight("-1px");
		jobDetLayout.addComponent(tblDets);
		
		return jobDetLayout;
	}
}
