package grisu.web;

import grisu.backend.model.job.JobStat;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

public class JobDetComponent extends CustomComponent {

	@AutoGenerated
	private Panel mainLayout;
	@AutoGenerated
	private VerticalLayout jobDetLayout;
	@AutoGenerated
	private HorizontalLayout subTypeLayout;
	@AutoGenerated
	private TextField txtSubType;
	@AutoGenerated
	private Label lblSubType;
	@AutoGenerated
	private HorizontalLayout subDescLayout;
	@AutoGenerated
	private TextArea txtSubDes;
	@AutoGenerated
	private Label lblSubDes;
	@AutoGenerated
	private HorizontalLayout statusLayout;
	@AutoGenerated
	private TextField txtStatus;
	@AutoGenerated
	private Label lblStatus;
	@AutoGenerated
	private HorizontalLayout fqanLayout;
	@AutoGenerated
	private TextField txtFqan;
	@AutoGenerated
	private Label lblFqan;
	@AutoGenerated
	private HorizontalLayout dnLayout;
	@AutoGenerated
	private TextField txtDn;
	@AutoGenerated
	private Label lblDn;
	@AutoGenerated
	private HorizontalLayout jobNameLayout;
	@AutoGenerated
	private TextField txtJobName;
	@AutoGenerated
	private Label lblJobName;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

		

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public JobDetComponent() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	public void setJobDetails(JobStat job)
	{

		txtJobName.setValue(job.getJobname());
		txtDn.setValue(job.getDn());
		txtFqan.setValue(job.getFqan());
		txtStatus.setValue(job.getStatus());
		txtSubDes.setValue(job.getSubmittedJobDescription());
		txtSubType.setValue(job.getSubmissionType());		
	}
	
	@AutoGenerated
	private Panel buildMainLayout() {
		// common part: create layout
		mainLayout = new Panel();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		
		jobDetLayout = buildJobDetLayout();
		mainLayout.setContent(jobDetLayout);
		
		return mainLayout;
	}
	
	@AutoGenerated
	private VerticalLayout buildJobDetLayout() {
		// common part: create layout
		jobDetLayout = new VerticalLayout();
		jobDetLayout.setImmediate(false);
		jobDetLayout.setWidth("538px");
		jobDetLayout.setHeight("340px");
		jobDetLayout.setMargin(true);
		
		// jobNameLayout
		jobNameLayout = buildJobNameLayout();
		jobDetLayout.addComponent(jobNameLayout);
		
		// dnLayout
		dnLayout = buildDnLayout();
		jobDetLayout.addComponent(dnLayout);
		
		// fqanLayout
		fqanLayout = buildFqanLayout();
		jobDetLayout.addComponent(fqanLayout);
		
		// statusLayout
		statusLayout = buildStatusLayout();
		jobDetLayout.addComponent(statusLayout);
		
		// subDescLayout
		subDescLayout = buildSubDescLayout();
		jobDetLayout.addComponent(subDescLayout);
		
		// subTypeLayout
		subTypeLayout = buildSubTypeLayout();
		jobDetLayout.addComponent(subTypeLayout);
		
		return jobDetLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildJobNameLayout() {
		// common part: create layout
		jobNameLayout = new HorizontalLayout();
		jobNameLayout.setImmediate(false);
		jobNameLayout.setWidth("-1px");
		jobNameLayout.setHeight("-1px");
		jobNameLayout.setMargin(false);
		
		// lblJobName
		lblJobName = new Label();
		lblJobName.setImmediate(false);
		lblJobName.setWidth("110px");
		lblJobName.setHeight("-1px");
		lblJobName.setValue("Job name");
		jobNameLayout.addComponent(lblJobName);
		
		// txtJobName
		txtJobName = new TextField();
		txtJobName.setImmediate(false);
		txtJobName.setWidth("360px");
		txtJobName.setHeight("-1px");
		txtJobName.setSecret(false);
		jobNameLayout.addComponent(txtJobName);
		
		return jobNameLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildDnLayout() {
		// common part: create layout
		dnLayout = new HorizontalLayout();
		dnLayout.setImmediate(false);
		dnLayout.setWidth("-1px");
		dnLayout.setHeight("-1px");
		dnLayout.setMargin(false);
		
		// lblDn
		lblDn = new Label();
		lblDn.setImmediate(false);
		lblDn.setWidth("110px");
		lblDn.setHeight("-1px");
		lblDn.setValue("DN");
		dnLayout.addComponent(lblDn);
		
		// txtDn
		txtDn = new TextField();
		txtDn.setImmediate(false);
		txtDn.setWidth("360px");
		txtDn.setHeight("-1px");
		txtDn.setSecret(false);
		dnLayout.addComponent(txtDn);
		
		return dnLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildFqanLayout() {
		// common part: create layout
		fqanLayout = new HorizontalLayout();
		fqanLayout.setImmediate(false);
		fqanLayout.setWidth("-1px");
		fqanLayout.setHeight("-1px");
		fqanLayout.setMargin(false);
		
		// lblFqan
		lblFqan = new Label();
		lblFqan.setImmediate(false);
		lblFqan.setWidth("110px");
		lblFqan.setHeight("-1px");
		lblFqan.setValue("Fqan");
		fqanLayout.addComponent(lblFqan);
		
		// txtFqan
		txtFqan = new TextField();
		txtFqan.setImmediate(false);
		txtFqan.setWidth("360px");
		txtFqan.setHeight("-1px");
		txtFqan.setSecret(false);
		fqanLayout.addComponent(txtFqan);
		
		return fqanLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildStatusLayout() {
		// common part: create layout
		statusLayout = new HorizontalLayout();
		statusLayout.setImmediate(false);
		statusLayout.setWidth("-1px");
		statusLayout.setHeight("-1px");
		statusLayout.setMargin(false);
		
		// lblStatus
		lblStatus = new Label();
		lblStatus.setImmediate(false);
		lblStatus.setWidth("110px");
		lblStatus.setHeight("-1px");
		lblStatus.setValue("Status");
		statusLayout.addComponent(lblStatus);
		
		// txtStatus
		txtStatus = new TextField();
		txtStatus.setImmediate(false);
		txtStatus.setWidth("360px");
		txtStatus.setHeight("-1px");
		txtStatus.setSecret(false);
		statusLayout.addComponent(txtStatus);
		
		return statusLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildSubDescLayout() {
		// common part: create layout
		subDescLayout = new HorizontalLayout();
		subDescLayout.setImmediate(false);
		subDescLayout.setWidth("-1px");
		subDescLayout.setHeight("-1px");
		subDescLayout.setMargin(false);
		
		// lblSubDes
		lblSubDes = new Label();
		lblSubDes.setImmediate(false);
		lblSubDes.setWidth("110px");
		lblSubDes.setHeight("-1px");
		lblSubDes.setValue("Submission Job Description");
		subDescLayout.addComponent(lblSubDes);
		
		// txtSubDes
		txtSubDes = new TextArea();
		txtSubDes.setImmediate(false);
		txtSubDes.setWidth("360px");
		txtSubDes.setHeight("86px");
		subDescLayout.addComponent(txtSubDes);
		
		return subDescLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildSubTypeLayout() {
		// common part: create layout
		subTypeLayout = new HorizontalLayout();
		subTypeLayout.setImmediate(false);
		subTypeLayout.setWidth("-1px");
		subTypeLayout.setHeight("-1px");
		subTypeLayout.setMargin(false);
		
		// lblSubType
		lblSubType = new Label();
		lblSubType.setImmediate(false);
		lblSubType.setWidth("110px");
		lblSubType.setHeight("-1px");
		lblSubType.setValue("Submission type");
		subTypeLayout.addComponent(lblSubType);
		
		// txtSubType
		txtSubType = new TextField();
		txtSubType.setImmediate(false);
		txtSubType.setWidth("360px");
		txtSubType.setHeight("-1px");
		txtSubType.setSecret(false);
		subTypeLayout.addComponent(txtSubType);
		
		return subTypeLayout;
	}
	
	public void populate(JobStat job){

		txtJobName.setValue(job.getJobname());
		txtDn.setValue(job.getDn());
		txtFqan.setValue(job.getFqan());
		txtStatus.setValue(job.getStatus());
		txtSubDes.setValue(job.getSubmittedJobDescription());
		txtSubType.setValue(job.getSubmissionType());				
	}
	
}
