package grisu.web;

import grisu.backend.model.job.JobStat;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

public class JobDetComponent extends CustomComponent {

	@AutoGenerated
	private Panel mainLayout;
	@AutoGenerated
	private VerticalLayout jobDetLayout;
	@AutoGenerated
	private HorizontalLayout subTypeLayout;
	@AutoGenerated
	private TextField txtSubType;
	@AutoGenerated
	private Label lblSubType;
	@AutoGenerated
	private HorizontalLayout subDescLayout;
	@AutoGenerated
	private TextArea txtSubDes;
	@AutoGenerated
	private Label lblSubDes;
	@AutoGenerated
	private HorizontalLayout statusLayout;
	@AutoGenerated
	private TextField txtStatus;
	@AutoGenerated
	private Label lblStatus;
	@AutoGenerated
	private HorizontalLayout fqanLayout;
	@AutoGenerated
	private TextField txtFqan;
	@AutoGenerated
	private Label lblFqan;
	@AutoGenerated
	private HorizontalLayout dnLayout;
	@AutoGenerated
	private TextField txtDn;
	@AutoGenerated
	private Label lblDn;
	@AutoGenerated
	private HorizontalLayout jobNameLayout;
	@AutoGenerated
	private TextField txtJobName;
	@AutoGenerated
	private Label lblJobName;
	@AutoGenerated
	private HorizontalLayout activeLayout;
	@AutoGenerated
	private TextField txtActive;
	@AutoGenerated
	private Label lblActive;
	@AutoGenerated
	private HorizontalLayout batchLayout;
	@AutoGenerated
	private TextField txtBatch;
	@AutoGenerated
	private Label lblBatch;

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public JobDetComponent() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		mainLayout.getContent().setSizeFull();
		mainLayout.setCaption("Job Details");
		mainLayout.setScrollable(true);
	}

	public void setJobDetails(JobStat job)
	{

		txtJobName.setValue(job.getJobname());
		txtDn.setValue(job.getDn());
		txtFqan.setValue(job.getFqan());
		txtStatus.setValue(job.getStatus());
		txtSubDes.setValue(job.getSubmittedJobDescription());
		txtSubType.setValue(job.getSubmissionType());		
	}
	
	@AutoGenerated
	private Panel buildMainLayout() {
		// common part: create layout
		mainLayout = new Panel();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		jobDetLayout = buildJobDetLayout();
		mainLayout.setContent(jobDetLayout);
		
		return mainLayout;
	}
	
	@AutoGenerated
	private VerticalLayout buildJobDetLayout() {
		// common part: create layout
		jobDetLayout = new VerticalLayout();
		jobDetLayout.setImmediate(false);
		jobDetLayout.setWidth("100%");
		jobDetLayout.setHeight("100%");
		jobDetLayout.setMargin(true);
		
		// jobNameLayout
		jobNameLayout = buildJobNameLayout();
		jobDetLayout.addComponent(jobNameLayout);
		
		// dnLayout
		dnLayout = buildDnLayout();
		jobDetLayout.addComponent(dnLayout);
		
		// fqanLayout
		fqanLayout = buildFqanLayout();
		jobDetLayout.addComponent(fqanLayout);
		
		// statusLayout
		statusLayout = buildStatusLayout();
		jobDetLayout.addComponent(statusLayout);
		
		// subDescLayout
		subDescLayout = buildSubDescLayout();
		jobDetLayout.addComponent(subDescLayout);
		
		// subTypeLayout
		subTypeLayout = buildSubTypeLayout();
		jobDetLayout.addComponent(subTypeLayout);
		
		// activeLayout
		activeLayout = buildActiveLayout();
		jobDetLayout.addComponent(activeLayout);

		// batchLayout
		batchLayout = buildBatchLayout();
		jobDetLayout.addComponent(batchLayout);
		
		return jobDetLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildJobNameLayout() {
		// common part: create layout
		jobNameLayout = new HorizontalLayout();
		jobNameLayout.setImmediate(false);
		//jobNameLayout.setWidth("-1px");
		jobNameLayout.setWidth("100%");
		jobNameLayout.setHeight("-1px");
		jobNameLayout.setMargin(false);
		
		// lblJobName
		lblJobName = new Label();
		lblJobName.setImmediate(false);
		lblJobName.setWidth("110px");
		lblJobName.setHeight("-1px");
		lblJobName.setValue("Job name");
		jobNameLayout.addComponent(lblJobName);
		
		// txtJobName
		txtJobName = new TextField();
		txtJobName.setImmediate(false);
		//txtJobName.setWidth("360px");
		txtJobName.setWidth("100%");
		txtJobName.setHeight("-1px");
		txtJobName.setSecret(false);
		jobNameLayout.addComponent(txtJobName);
		jobNameLayout.setExpandRatio(txtJobName, 1.0f);
		
		return jobNameLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildDnLayout() {
		// common part: create layout
		dnLayout = new HorizontalLayout();
		dnLayout.setImmediate(false);
		//dnLayout.setWidth("-1px");
		dnLayout.setWidth("100%");
		dnLayout.setHeight("-1px");
		dnLayout.setMargin(false);
		
		// lblDn
		lblDn = new Label();
		lblDn.setImmediate(false);
		lblDn.setWidth("110px");
		lblDn.setHeight("-1px");
		lblDn.setValue("DN");
		dnLayout.addComponent(lblDn);
		
		// txtDn
		txtDn = new TextField();
		txtDn.setImmediate(false);
		//txtDn.setWidth("360px");
		txtDn.setWidth("100%");
		txtDn.setHeight("-1px");
		txtDn.setSecret(false);
		dnLayout.addComponent(txtDn);
		dnLayout.setExpandRatio(txtDn, 1.0f);
		
		return dnLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildFqanLayout() {
		// common part: create layout
		fqanLayout = new HorizontalLayout();
		fqanLayout.setImmediate(false);
		//fqanLayout.setWidth("-1px");
		fqanLayout.setWidth("100%");
		fqanLayout.setHeight("-1px");
		fqanLayout.setMargin(false);
		
		// lblFqan
		lblFqan = new Label();
		lblFqan.setImmediate(false);
		lblFqan.setWidth("110px");
		lblFqan.setHeight("-1px");
		lblFqan.setValue("Fqan");
		fqanLayout.addComponent(lblFqan);
		
		// txtFqan
		txtFqan = new TextField();
		txtFqan.setImmediate(false);
//		txtFqan.setWidth("360px");
		txtFqan.setWidth("100%");
		txtFqan.setHeight("-1px");
		txtFqan.setSecret(false);
		fqanLayout.addComponent(txtFqan);
		fqanLayout.setExpandRatio(txtFqan, 1.0f);
		
		return fqanLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildStatusLayout() {
		// common part: create layout
		statusLayout = new HorizontalLayout();
		statusLayout.setImmediate(false);
//		statusLayout.setWidth("-1px");
		statusLayout.setWidth("100%");
		statusLayout.setHeight("-1px");
		statusLayout.setMargin(false);
		
		// lblStatus
		lblStatus = new Label();
		lblStatus.setImmediate(false);
		lblStatus.setWidth("110px");
		lblStatus.setHeight("-1px");
		lblStatus.setValue("Status");
		statusLayout.addComponent(lblStatus);
		
		// txtStatus
		txtStatus = new TextField();
		txtStatus.setImmediate(false);
//		txtStatus.setWidth("360px");
		txtStatus.setWidth("100%");
		txtStatus.setHeight("-1px");
		txtStatus.setSecret(false);
		statusLayout.addComponent(txtStatus);
		statusLayout.setExpandRatio(txtStatus, 1.0f);
		
		return statusLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildSubDescLayout() {
		// common part: create layout
		subDescLayout = new HorizontalLayout();
		subDescLayout.setImmediate(false);
		//subDescLayout.setWidth("-1px");
		subDescLayout.setWidth("100%");
		subDescLayout.setHeight("-1px");
		subDescLayout.setMargin(false);
		
		// lblSubDes
		lblSubDes = new Label();
		lblSubDes.setImmediate(false);
		lblSubDes.setWidth("110px");
		lblSubDes.setHeight("-1px");
		lblSubDes.setValue("Submission Job Description");
		subDescLayout.addComponent(lblSubDes);
		
		// txtSubDes
		txtSubDes = new TextArea();
		txtSubDes.setImmediate(false);
//		txtSubDes.setWidth("360px");
		txtSubDes.setWidth("100%");
		txtSubDes.setHeight("86px");
		subDescLayout.addComponent(txtSubDes);
		subDescLayout.setExpandRatio(txtSubDes, 1.0f);
		
		return subDescLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildSubTypeLayout() {
		// common part: create layout
		subTypeLayout = new HorizontalLayout();
		subTypeLayout.setImmediate(false);
		//subTypeLayout.setWidth("-1px");
		subTypeLayout.setWidth("100%");
		subTypeLayout.setHeight("-1px");
		subTypeLayout.setMargin(false);
		
		// lblSubType
		lblSubType = new Label();
		lblSubType.setImmediate(false);
		lblSubType.setWidth("110px");
		lblSubType.setHeight("-1px");
		lblSubType.setValue("Submission type");
		subTypeLayout.addComponent(lblSubType);
		
		// txtSubType
		txtSubType = new TextField();
		txtSubType.setImmediate(false);
		//txtSubType.setWidth("360px");
		txtSubType.setWidth("100%");
		txtSubType.setHeight("-1px");
		txtSubType.setSecret(false);
		subTypeLayout.addComponent(txtSubType);
		subTypeLayout.setExpandRatio(txtSubType, 1.0f);
		
		return subTypeLayout;
	}
	
	@AutoGenerated
	private HorizontalLayout buildActiveLayout() {
		// common part: create layout
		activeLayout = new HorizontalLayout();
		activeLayout.setImmediate(false);
		activeLayout.setWidth("-1px");
		activeLayout.setHeight("-1px");
		activeLayout.setMargin(false);
		
		// lblSubType
		lblActive = new Label();
		lblActive.setImmediate(false);
		lblActive.setWidth("110px");
		lblActive.setHeight("-1px");
		lblActive.setValue("Active");
		activeLayout.addComponent(lblActive);
		
		// txtSubType
		txtActive = new TextField();
		txtActive.setImmediate(false);
		txtActive.setWidth("360px");
		txtActive.setHeight("-1px");
		txtActive.setSecret(false);
		activeLayout.addComponent(txtActive);
		
		return activeLayout;
	}	
	
	@AutoGenerated
	private HorizontalLayout buildBatchLayout() {
		// common part: create layout
		batchLayout = new HorizontalLayout();
		batchLayout.setImmediate(false);
		batchLayout.setWidth("-1px");
		batchLayout.setHeight("-1px");
		batchLayout.setMargin(false);
		
		// lblSubType
		lblBatch = new Label();
		lblBatch.setImmediate(false);
		lblBatch.setWidth("110px");
		lblBatch.setHeight("-1px");
		lblBatch.setValue("Batch job");
		batchLayout.addComponent(lblBatch);
		
		// txtSubType
		txtBatch = new TextField();
		txtBatch.setImmediate(false);
		txtBatch.setWidth("360px");
		txtBatch.setHeight("-1px");
		txtBatch.setSecret(false);
		batchLayout.addComponent(txtBatch);
		
		return batchLayout;
	}	
	
	public void populate(JobStat job){

		if(job!=null){
			txtJobName.setValue(job.getJobname());
			txtDn.setValue(job.getDn());
			txtFqan.setValue(job.getFqan());
			txtStatus.setValue(job.getStatus());
			txtSubDes.setValue(job.getSubmittedJobDescription());
			txtSubType.setValue(job.getSubmissionType());
			txtActive.setValue(job.isActive());
			txtBatch.setValue(job.isBatchJob());
		}
	}
	
}
