package grisu.web;

import java.util.List;

import javassist.bytecode.Descriptor.Iterator;
import grisu.backend.hibernate.JobStatDAO;
import grisu.backend.model.User;
import grisu.backend.model.job.JobStat;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Item;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.data.util.BeanItemContainer;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Panel;
import com.vaadin.ui.Table;
import com.vaadin.ui.VerticalLayout;

public class JobTable extends CustomComponent {

	@AutoGenerated
	private Panel mainLayout;
	@AutoGenerated
	private Table tblJobs;

	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	
	
	public JobTable(String caption) {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here

		tblJobs.setSelectable(true);
		tblJobs.setColumnReorderingAllowed(true);
		mainLayout.setCaption(caption);
		

	}

	public void addListener(ValueChangeListener valueChangeListener) {
		// TODO Auto-generated method stub
		tblJobs.addListener(valueChangeListener);
	}

	public void setTable(BeanItemContainer<JobStat> jobStatContainer) {
		// TODO Auto-generated method stub
		tblJobs.setContainerDataSource(jobStatContainer);
	}



	public Object getTabcleClickVal() {
		// TODO Auto-generated method stub
		return tblJobs.getValue();
	}

	@AutoGenerated
	private Panel buildMainLayout() {
		// common part: create layout
		mainLayout = new Panel();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// tblUser
		tblJobs = new Table();
		tblJobs.setImmediate(true);
		tblJobs.setWidth("-1px");
		tblJobs.setHeight("100%");
		mainLayout.addComponent(tblJobs);
		
		return mainLayout;
	}

	public void populate(String dn) {
		// TODO Auto-generated method stub
		
		JobStatDAO jsDao = new JobStatDAO();
		List<JobStat> jobs=jsDao.findJobByDN(dn, true);
		BeanItemContainer<JobStat> jobContainer = new BeanItemContainer<JobStat>(JobStat.class);
		System.out.println(jobs.size()+"..."+dn);
		
		jobContainer.addAll(jobs);
		
		tblJobs.setContainerDataSource(jobContainer);

		tblJobs.setVisibleColumns(new Object [] {"jobname", "status", "fqan"});
	}

	public Object getSelectedJob() {
		// TODO Auto-generated method stub
		return tblJobs.getValue();
	}

}
